#Standard libraries
import argparse
import subprocess
from pathlib import Path
from Bio import SeqIO

#Local imports form utils.py to reuse declared functions
from utils import ensure_dir,run_command,find_fastas

#Searches for a FASTA file in the given path  
def resolve_fasta(path: Path) -> Path:
    if path.is_file():
        return path

    fastas = find_fastas(path)
    return fastas[0]


# Run CD-HIT clustering on protein sequences file
def run_cdhit(input_fasta: Path, output_prefix: Path, identity: float = 0.9):
    output_fasta = output_prefix.with_suffix(".faa")
    clstr_file = output_fasta.with_suffix(".faa.clstr")
    #Avoids re-execution if output files already exist
    if output_fasta.exists() and clstr_file.exists():
        print(f"[SKIP] CD-HIT already computed")
        return output_fasta, clstr_file
    # Builds the command to run CD-HIT 
    cmd = [ "cd-hit", "-i", str(input_fasta), "-o", str(output_fasta), "-c", str(identity),"-n", "5", "-d", "0"]
    run_command(cmd)
    return output_fasta, clstr_file


# Filters the clusters generated by CD-HIT based by a minimum size 
def parse_clusters(clstr_file: Path, min_size: int):
    clusters = []
    current = [] # Stores current cluster
    with open(clstr_file) as f:
        for line in f:
            line = line.strip() # Removes whitespace characters 
            if line.startswith(">Cluster"):
                if current:
                    clusters.append(current)
                current = [] # Starts a new cluster
            else:
                seq_id = line.split(">")[1].split("...")[0] #Keep only seq_id (0 764aa, >seq_id... *)
                current.append(seq_id)
        if current:
            clusters.append(current) # Adds the last cluster if exists
    # Filter cluster by size and build statistics
    filtered = [c for c in clusters if len(c) >= min_size]
    stats = {"total_clusters": len(clusters), "filtered_clusters": len(filtered), "min_size": min_size}
    return filtered, stats


# Load FASTA records
def load_fasta(fasta_path: Path):
    return {rec.id: rec for rec in SeqIO.parse(fasta_path, "fasta")}


# Write each clusters on a FASTA file 
def write_clusters(clusters, fasta_dict, out_dir: Path):
    ensure_dir(out_dir)
    # For each cluster creates a file cluster_i.faa
    for i, cluster in enumerate(clusters, 1):
        out_file = out_dir / f"cluster_{i}.faa"
        # Write all sequences of the cluster in the file
        with open(out_file, "w") as f:
            for seq_id in cluster:
                if seq_id in fasta_dict:
                    SeqIO.write(fasta_dict[seq_id], f, "fasta")


# Write a TSV file with the metadata of the clusters 
def write_metadata(clusters, fasta_dict, out_file: Path):
    with open(out_file, "w") as f:
        # Write header
        f.write("cluster_id\tprotein_id\tdescription\n")
        for i, cluster in enumerate(clusters, 1):
            for seq_id in cluster:
                rec = fasta_dict.get(seq_id) # Retrieve FASTA record
                if rec:
                    f.write(f"{i}\t{seq_id}\t{rec.description}\n")


# Parse the input arguments
def parse_args():
    parser = argparse.ArgumentParser( description="Run CD-HIT for multiple query FASTA files" )
    parser.add_argument( "--input_dir", type=Path, required=True)
    parser.add_argument( "--output_dir", type=Path, required=True)
    parser.add_argument( "--cluster_threshold", type=float, default=0.9)
    parser.add_argument( "--cluster_size", type=int, default=5)
    return parser.parse_args()


def main():
    # Read the parameters
    args = parse_args()
    ensure_dir(args.output_dir)
    prefix = args.output_dir / "cdhit"
    fasta_out, clstr_file = run_cdhit(args.input_dir, prefix, args.cluster_threshold)
    clusters, stat = parse_clusters(clstr_file, args.cluster_size)
    fasta_dict = load_fasta(args.input_dir) # Load original FASTA files 
    # Export cluster FASTA files
    write_clusters(clusters, fasta_dict, args.output_dir / "clusters_raw")
    # Export cluster metadata table
    write_metadata(clusters, fasta_dict, args.output_dir / "clusters.tsv")

if __name__ == "__main__":
    main()
