#Standard libraries
import argparse
from pathlib import Path
from Bio import SeqIO # Read and write FASTA sequence files
import json # For handling JSON data, used for stats output

#Local imports form utils.py to reuse declared functions
from utils import write_jsonl,ensure_dir,validate_dir,build_stats


# Provides protein and organism statistics for one cluster
def process_cluster(cluster_file: Path):
    organisms = set()
    total = 0
    #Counts the number of sequences in the cluster file
    for record in SeqIO.parse(cluster_file, "fasta"):
        total += 1
        org = record.id.split("|")[0]  # ID format is "organism|protein_id"
        organisms.add(org)
    return {"cluster": cluster_file.name,"proteins": total, "organisms": len(organisms)}


# Filter clusters according to a minimum protein number and a minimum organism presence threshold
def filter_clusters(input_dir: Path, output_dir: Path, stats_file: Path, min_proteins: int, min_organisms: int):
    ensure_dir(output_dir)
    ensure_dir(stats_file.parent)
    # gets all cluster_*.faa files 
    cluster_files = list(input_dir.glob("*.faa"))
    total_clusters = 0
    kept_clusters = 0
    removed_clusters = 0
    total_proteins_kept = 0
    total_organisms_kept = 0
    # Opens in writing mode the statistics file in JSONL format
    with open(stats_file, "w") as stats_out:
        for cluster_file in sorted(cluster_files):
            total_clusters += 1
            # Computes the statistics for the cluster that asses the thresholds
            stat = process_cluster(cluster_file)
            keep = (stat["proteins"] >= min_proteins and stat["organisms"] >= min_organisms)
            if keep:
                kept_clusters += 1
                total_proteins_kept += stat["proteins"]
                total_organisms_kept += stat["organisms"]
                out_file = output_dir / cluster_file.name
                out_file.write_text(cluster_file.read_text())
            #Remove invalid clusters 
            else:
                removed_clusters += 1
            #Stores the filtering decision
            stat["kept"] = keep
            write_jsonl(stats_out, stat)  # Saves metrics
    # Builds the global summary
    summary = {"total_clusters": total_clusters,"kept_clusters": kept_clusters,
        "removed_clusters": removed_clusters,"total_proteins_kept": total_proteins_kept,
        "percentage_kept": round((kept_clusters / total_clusters) * 100, 2) if total_clusters else 0.0,
        "avg_proteins_per_cluster":round(total_proteins_kept / kept_clusters, 2) if kept_clusters else 0.0,
        "avg_organisms_per_cluster":round(total_organisms_kept / kept_clusters, 2) if kept_clusters else 0.0}
    # Adds the global summary to the end of statistics file
    with open(stats_file, "a") as stats_out:
        write_jsonl(stats_out, {"SUMMARY": summary})
    # Print the global summary to the console
    print("\n[SUMMARY]")
    for k, v in summary.items():
        print(f"{k}: {v}")


# Extract a representative sequence IDs for each cluster from CD-HIT output file ( * )
def get_representative_ids(cdhit_dir: Path):
     # Gets all the .clstr file generated by CD-HIT if there are no files raises an error
    clstr_files = list(cdhit_dir.glob("*.clstr"))
    if not clstr_files:
        raise FileNotFoundError(f"No .clstr file found in {cdhit_dir}")
    clstr_path = clstr_files[0]
    rep_ids = set()
    with open(clstr_path) as f:
        for line in f:
            line = line.strip()
            # Representative sequences are marked with *  (0 764aa, >NC_000962.3_protein|NP_217790.1... *)            
            if "*" in line:  
                part = line.split(">")[1]        # NP_217790.1... 
                rep_id = part.split("...")[0]    # NP_217790.1
                rep_ids.add(rep_id)
    
    return rep_ids


#Create a new FASTA file with the representative sequences of the clusters that passed the filtering step
def extract_representatives_from_filtered(input_dir: Path, rep_ids: set, output_dir: Path):
    ensure_dir(output_dir)
    out_fasta = output_dir / "representatives.faa"
    with open(out_fasta, "w") as out:
        # Executed in all cluster_*.faa
        for faa_file in sorted(input_dir.glob("cluster_*.faa")):
            for record in SeqIO.parse(faa_file, "fasta"):
                if record.id in rep_ids:
                    SeqIO.write(record, out, "fasta")
    return out_fasta


# Parse the input arguments
def parse_args():
    parser = argparse.ArgumentParser(description="Filter clusters based on protein and organism thresholds")
    parser.add_argument("--input_dir", type=Path, required=True)
    parser.add_argument("--output_dir", type=Path, required=True)
    parser.add_argument("--stats_file", type=Path, required=True)
    parser.add_argument("--min_proteins", type=int, default=5)
    parser.add_argument("--min_organisms", type=int, default=5)
    parser.add_argument("--finalcluster_dir", type=Path, required=True)
    return parser.parse_args()


def main():
    # Read the parameters
    args = parse_args()
    validate_dir(args.input_dir)
    validate_dir(args.finalcluster_dir)
    # Applies the filtering criteria to the clusters 
    filter_clusters(args.input_dir, args.output_dir, args.stats_file, args.min_proteins, args.min_organisms)
    # Extract representative sequence IDs and creates a file with these representative sequences 
    rep_ids = get_representative_ids(args.finalcluster_dir)
    extract_representatives_from_filtered(args.output_dir, rep_ids, args.finalcluster_dir)

if __name__ == "__main__":
    main()